### ISSUE TITLE
Not able to install via portainer

### ISSUE THREAD

**Issue by xiNeRoar** [doihaveto/jellix#1]
![image](https://github.com/doihaveto/jellix/assets/66216186/815a4008-30d1-4508-9a5f-f3ea011b9387)
portainer says the format is wrong

**Comment by doihaveto** [comment]
Try this format:
```
version: '3.9'

services:
  jellix:
    container_name: jellix
    build: ./jellix
    restart: unless-stopped 
    environment:
      - API_URL=http://localhost:5000/
    ports:
      - 3000:3000
```

And don't forget to replace the URL with your jellyfin URL

**Comment by RemmyLee** [comment]
Clone the repository and build the image.

`docker build -t jellix:1.0 .`

Then add an image line.

```
version: '3.9'

services:
  jellix:
    image: jellix:1.0
    container_name: jellix
    build: ./jellix
    restart: unless-stopped 
    environment:
      - API_URL=http://127.0.0.18096/
    ports:
      - 3000:3000

```
